<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_gazebo</name>
  <version>0.1.0</version>
  <description>Package for setting up and launching gazebo related options</description>
  <maintainer email="jeppha@mmmi.sdu.dk"> Jeppe Hansen</maintainer>
  <license>MIT</license>

  <buildtool_depend>robot_description</buildtool_depend>
  <buildtool_depend>robot_control</buildtool_depend>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
