<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robot_bringup</name>
  <version>0.1.0</version>
  <description>Package for bringing up the robot in an intercropping world.</description>
  <maintainer email="jeppha@mmmi.sdu.dk"> Jeppe Hansen</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>intercropping_gz</exec_depend>
  <exec_depend>robot_gazebo</exec_depend>
  <exec_depend>soil_sampler_description</exec_depend>

  <exec_depend>ros_gz_sim</exec_depend>
  <!-- <exec_depend>controller_manager</exec_depend> -->
  
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
